import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', loadComponent: () => import('./pages/home/home').then(m => m.Home) },
  { path: 'components/button', loadComponent: () => import('./pages/button/button').then(m => m.ButtonComponent) },
  { path: 'components/inputtext', loadComponent: () => import('./pages/inputtext/inputtext').then(m => m.Inputtext) },
  { path: 'components/inputtextarea', loadComponent: () => import('./pages/inputtextarea/inputtextarea').then(m => m.Inputtextarea) },
  { path: 'components/card', loadComponent: () => import('./pages/card/card').then(m => m.CardComponent) },
  { path: 'components/checkbox', loadComponent: () => import('./pages/checkbox/checkbox').then(m => m.CheckboxComponent) },
  { path: 'components/radiobutton', loadComponent: () => import('./pages/radiobutton/radiobutton').then(m => m.Radiobutton) },
  { path: 'components/colorpicker', loadComponent: () => import('./pages/colorpicker/colorpicker').then(m => m.Colorpicker) },
  { path: 'components/select', loadComponent: () => import('./pages/select/select').then(m => m.Select) },
  { path: 'components/password', loadComponent: () => import('./pages/password/password').then(m => m.Password) },
  { path: 'components/inputnumber', loadComponent: () => import('./pages/inputnumber/inputnumber').then(m => m.Inputnumber) },
  { path: 'components/datepicker', loadComponent: () => import('./pages/datepicker/datepicker').then(m => m.Datepicker) },
  { path: 'components/slider', loadComponent: () => import('./pages/slider/slider').then(m => m.Slider) },
  { path: 'components/rating', loadComponent: () => import('./pages/rating/rating').then(m => m.Rating) },
  { path: 'components/toggleswitch', loadComponent: () => import('./pages/toggleswitch/toggleswitch').then(m => m.Toggleswitch) },
  { path: 'components/cascadeselect', loadComponent: () => import('./pages/cascadeselect/cascadeselect').then(m => m.Cascadeselect) },
  { path: 'components/floatlabel', loadComponent: () => import('./pages/floatlabel/floatlabel').then(m => m.Floatlabel) },
  { path: 'components/autocomplete', loadComponent: () => import('./pages/autocomplete/autocomplete').then(m => m.AutocompleteComponent) },
  { path: 'components/inputmask', loadComponent: () => import('./pages/inputmask/inputmask').then(m => m.Inputmask) },
  { path: 'components/iconfield', loadComponent: () => import('./pages/iconfield/iconfield').then(m => m.IconfieldComponent) },
  { path: 'components/ifta-label', loadComponent: () => import('./pages/ifta-label/ifta-label').then(m => m.IftaLabelComponent) },
  { path: 'components/ift-label', loadComponent: () => import('./pages/ift-label/ift-label').then(m => m.IftLabelComponent) },
  { path: 'components/speed-dial', loadComponent: () => import('./pages/speed-dial/speed-dial').then(m => m.SpeedDialComponent) },
  { path: 'components/split-button', loadComponent: () => import('./pages/split-button/split-button').then(m => m.SplitButtonComponent) },
  { path: 'components/divider', loadComponent: () => import('./pages/divider/divider').then(m => m.DividerComponent) },
  { path: 'components/fieldset', loadComponent: () => import('./pages/fieldset/fieldset').then(m => m.FieldsetComponent) },
  { path: 'components/toolbar', loadComponent: () => import('./pages/toolbar/toolbar').then(m => m.ToolbarComponent) },
  
  // High-Priority Components
  { path: 'components/table', loadComponent: () => import('./pages/table/table').then(m => m.TableComponent) },
  { path: 'components/dialog', loadComponent: () => import('./pages/dialog/dialog').then(m => m.DialogComponent) },
  { path: 'components/tabs', loadComponent: () => import('./pages/tabs/tabs').then(m => m.TabsDemoComponent) },
  { path: 'components/accordion', loadComponent: () => import('./pages/accordion/accordion').then(m => m.AccordionComponent) },
  { path: 'components/tooltip', loadComponent: () => import('./pages/tooltip/tooltip').then(m => m.TooltipComponent) },
  { path: 'components/progressbar', loadComponent: () => import('./pages/progressbar/progressbar').then(m => m.Progressbar) },
  { path: 'components/badge', loadComponent: () => import('./pages/badge/badge').then(m => m.Badge) },
  { path: 'components/avatar', loadComponent: () => import('./pages/avatar/avatar').then(m => m.Avatar) },
  { path: 'components/chip', loadComponent: () => import('./pages/chip/chip').then(m => m.Chip) },
  { path: 'components/upload', loadComponent: () => import('./pages/upload/upload').then(m => m.UploadComponent) },
  
  // Medium-Priority Components
  { path: 'components/panel', loadComponent: () => import('./pages/panel/panel').then(m => m.PanelComponent) },
  { path: 'components/divider', loadComponent: () => import('./pages/divider/divider').then(m => m.DividerComponent) },
  { path: 'components/fieldset', loadComponent: () => import('./pages/fieldset/fieldset').then(m => m.FieldsetComponent) },
  { path: 'components/stepper', loadComponent: () => import('./pages/stepper/stepper').then(m => m.StepperComponent) },
  { path: 'components/tabs', loadComponent: () => import('./pages/tabs/tabs').then(m => m.TabsDemoComponent) },
  { path: 'components/confirmdialog', loadComponent: () => import('./pages/confirmdialog/confirmdialog').then(m => m.ConfirmDialogComponent) },
  { path: 'components/confirmpopup', loadComponent: () => import('./pages/confirmpopup/confirmpopup').then(m => m.ConfirmPopupComponent) },
  { path: 'components/dialog', loadComponent: () => import('./pages/dialog/dialog').then(m => m.DialogComponent) },
  { path: 'components/drawer', loadComponent: () => import('./pages/drawer/drawer').then(m => m.DrawerComponent) },
  { path: 'components/dynamicdialog', loadComponent: () => import('./pages/dynamicdialog/dynamicdialog').then(m => m.DynamicDialogComponent) },
  { path: 'components/popover', loadComponent: () => import('./pages/popover/popover').then(m => m.PopoverComponent) },
  { path: 'components/tooltip', loadComponent: () => import('./pages/tooltip/tooltip').then(m => m.TooltipComponent) },
  { path: 'components/toolbar', loadComponent: () => import('./pages/toolbar/toolbar').then(m => m.ToolbarComponent) },
  { path: 'components/scrollpanel', loadComponent: () => import('./pages/scrollpanel/scrollpanel').then(m => m.ScrollPanelComponent) },
  { path: 'components/splitter', loadComponent: () => import('./pages/splitter/splitter').then(m => m.SplitterComponent) },
  { path: 'components/menu', loadComponent: () => import('./pages/menu/menu').then(m => m.MenuComponent) },
  
  // Additional Medium-Priority Components
  { path: 'components/menubar', loadComponent: () => import('./pages/menubar/menubar').then(m => m.MenubarComponent) },
  { path: 'components/contextmenu', loadComponent: () => import('./pages/contextmenu/contextmenu').then(m => m.ContextMenuComponent) },
  { path: 'components/dock', loadComponent: () => import('./pages/dock/dock').then(m => m.DockComponent) },
  { path: 'components/breadcrumb', loadComponent: () => import('./pages/breadcrumb/breadcrumb').then(m => m.BreadcrumbComponent) },
  { path: 'components/tieredmenu', loadComponent: () => import('./pages/tieredmenu/tieredmenu').then(m => m.Tieredmenu) },
  { path: 'components/carousel', loadComponent: () => import('./pages/carousel/carousel').then(m => m.CarouselComponent) },
  { path: 'components/galleria', loadComponent: () => import('./pages/galleria/galleria').then(m => m.GalleriaComponent) },
  { path: 'components/image', loadComponent: () => import('./pages/image/image').then(m => m.ImageComponent) },
  { path: 'components/tag', loadComponent: () => import('./pages/tag/tag').then(m => m.TagComponent) },
  { path: 'components/skeleton', loadComponent: () => import('./pages/skeleton/skeleton').then(m => m.SkeletonComponent) },
  { path: 'components/overlaypanel', loadComponent: () => import('./pages/overlaypanel/overlaypanel').then(m => m.Overlaypanel) },
  { path: 'components/sidebar', loadComponent: () => import('./pages/sidebar/sidebar').then(m => m.SidebarComponent) },
  { path: 'components/confirmdialog', loadComponent: () => import('./pages/confirmdialog/confirmdialog').then(m => m.ConfirmDialogComponent) },
  { path: 'components/fileupload', loadComponent: () => import('./pages/fileupload/fileupload').then(m => m.Fileupload) },
  { path: 'components/listbox', loadComponent: () => import('./pages/listbox/listbox').then(m => m.ListboxComponent) },
  { path: 'components/selectbutton', loadComponent: () => import('./pages/selectbutton/selectbutton').then(m => m.SelectbuttonComponent) },
  { path: 'components/togglebutton', loadComponent: () => import('./pages/togglebutton/togglebutton').then(m => m.TogglebuttonComponent) },
  { path: 'components/treeselect', loadComponent: () => import('./pages/treeselect/treeselect').then(m => m.TreeselectComponent) },
  { path: 'components/inputotp', loadComponent: () => import('./pages/inputotp/inputotp').then(m => m.InputotpComponent) },
  { path: 'components/inputgroup', loadComponent: () => import('./pages/inputgroup/inputgroup').then(m => m.InputgroupComponent) },
  { path: 'components/captcha', loadComponent: () => import('./pages/captcha/captcha').then(m => m.CaptchaComponent) },
  { path: 'components/tree', loadComponent: () => import('./pages/tree/tree').then(m => m.TreeComponent) },
  { path: 'components/tree-table', loadComponent: () => import('./pages/tree-table/tree-table').then(m => m.TreeTableComponent) },
  { path: 'components/dataview', loadComponent: () => import('./pages/data-view/data-view').then(m => m.DataViewComponent) },
  { path: 'components/orderlist', loadComponent: () => import('./pages/orderlist/orderlist').then(m => m.OrderlistComponent) },
  { path: 'components/orgchart', loadComponent: () => import('./pages/orgchart/orgchart').then(m => m.OrgchartComponent) },
  { path: 'components/paginator', loadComponent: () => import('./pages/paginator/paginator').then(m => m.PaginatorComponent) },
  { path: 'components/picklist', loadComponent: () => import('./pages/picklist/picklist').then(m => m.PicklistComponent) },
  { path: 'components/timeline', loadComponent: () => import('./pages/timeline/timeline').then(m => m.TimelineComponent) },
  { path: 'components/tree', loadComponent: () => import('./pages/tree/tree').then(m => m.TreeComponent) },
  { path: 'components/treetable', loadComponent: () => import('./pages/tree-table/tree-table').then(m => m.TreeTableComponent) },
  { path: 'components/virtualscroller', loadComponent: () => import('./pages/virtual-scroller/virtual-scroller').then(m => m.VirtualScrollerComponent) },
  { path: 'components/panel', loadComponent: () => import('./pages/panel/panel').then(m => m.PanelComponent) },
  { path: 'components/scrollpanel', loadComponent: () => import('./pages/scrollpanel/scrollpanel').then(m => m.ScrollPanelComponent) },
  { path: 'components/splitter', loadComponent: () => import('./pages/splitter/splitter').then(m => m.SplitterComponent) },
  { path: 'components/stepper', loadComponent: () => import('./pages/stepper/stepper').then(m => m.StepperComponent) },
  { path: 'components/splitbutton', loadComponent: () => import('./pages/splitbutton/splitbutton').then(m => m.SplitbuttonComponent) },
  { path: 'components/chart', loadComponent: () => import('./pages/chart/chart').then(m => m.ChartComponent) },
  { path: 'components/editor', loadComponent: () => import('./pages/editor/editor').then(m => m.EditorComponent) },
  { path: 'components/knob', loadComponent: () => import('./pages/knob/knob').then(m => m.KnobComponent) },
  { path: 'components/progressspinner', loadComponent: () => import('./pages/progressspinner/progressspinner').then(m => m.ProgressspinnerComponent) },
  { path: 'components/ripple', loadComponent: () => import('./pages/ripple/ripple').then(m => m.RippleComponent) },
  { path: 'components/scrolltop', loadComponent: () => import('./pages/scrolltop/scrolltop').then(m => m.ScrolltopComponent) },
  { path: 'components/focustrap', loadComponent: () => import('./pages/focustrap/focustrap').then(m => m.FocustrapComponent) },
  { path: 'components/styleclass', loadComponent: () => import('./pages/styleclass/styleclass').then(m => m.StyleclassComponent) },
  { path: 'components/keyfilter', loadComponent: () => import('./pages/keyfilter/keyfilter').then(m => m.KeyfilterComponent) }
];