name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  releases: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'synerity-ui/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd synerity-ui
          npm install
        
      - name: Install Angular CLI
        run: |
          cd synerity-ui
          npm install -g @angular/cli
        
      - name: Build library
        run: |
          cd synerity-ui
          ng build ui-lib
        
      - name: Publish to NPM
        run: |
          cd synerity-ui/dist/ui-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }} of @synerity/ui npm package" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
